### PR TITLE
DatePicker for inline edit

### PR DESCRIPTION
**Pull request by cgrimsleyTechtonic**
Additionally fixed the multiple put calls and got all edits to wrap into a single call. unable to test higher level tasks yet, will need to check that in the future. also the dates dont rerender in real time, done must be clicked for the call to fire cus the response is what rerenders the changes. the RIEK automatically displays changes so thats why there is a discrepancy there. will have to work on having the date change in real time in the future.

### CODE REVIEW

**Comment by umorenovanderlaanTechtonic** [comment]
Excellent work Cody! Only change I can think to make is to disallow the selection of a due date in the past, which the pop up date picker currently allows. We might also fiddle with how that displays, but overall the functionality is excellent. A+!

**Comment by jhernandezinzunzaTechtonic** [comment]
Looks awesome, but I cant change months at all :(

**Review by jhernandezinzunzaTechtonic — CHANGES_REQUESTED** [review]
Can we change months or no?

**Comment by cgrimsleyTechtonic** [comment]
Made corrections. works as requested. two small issues exist, you can spam the toggles and get empty puts to fire, might be able to handle that in the req itself in the future. additionally to get out of the calendar "modal" you MUST select a date or otherwise reload the page, ive looked for ways around this but im coming up short on any quick and easy solutions.

**Review by jhernandezinzunzaTechtonic — APPROVED** [review]

**Pull request merged**
